### PR TITLE
config: fix hibernate and Energy Saver display

### LINKED ISSUE #107: The "battery" option in Energy Saver
OC v2.3.1
image
I think it shoushouldn't be visible on mac mini

### LINKED ISSUE #193: Device powers off after > 1 day standby
Seems like if left in standby for a long enough time, the NUC just powers off. This is even though dark wakes happen periodically. I observe the shut down only happening if no user interaction happens for a long enough time (at least a day or two). I suspect it might be trying to hibernate and then shutting off.

### PR DESCRIPTION
**Pull request by osy86**
Incorrect FADT profile makes a Battery 0% show up in Energy Saver
preference pane. Fixes #107

Incorrect OC HibernateMode forces OSX to restart when in deep sleep. This
should allow hibernation to work. Fixes #193

### CODE REVIEW

**Comment by chrisallen** [comment]
Oooh awesome!

**Comment by osy86** [comment]
Not sure if it works yet, testing it myself.

**Comment by goodbest** [comment]
I can confirm the mod is working under BIOS 0059 and 10.15.3
Nuc will not auto-reboot if you leave it asleep for one or a few days.

Battery 0% will also not show in preferences.

**Comment by osy86** [comment]
@goodbest hmm it wasn’t working for me. Are you sure you didn’t disable standby with pmset?

**Comment by chrisallen** [comment]
Any chance of getting this merged?

**Comment by osy86** [comment]
I mean it doesn't work for me so I hesitate to merge it as is. There needs to be some changes to handle Intel's use of RTC ram and not collide with OSX.

**Comment by hongkongkiwi** [comment]
Is this in the latest release?

**Comment by osy86** [comment]
Thanks for the confirmation. I will upgrade to 059 and try it myself and will merge it if I don’t run into any issues.

**Comment by osy86** [comment]
Update: I’ve updated my bios to 059 and it still doesn’t work with my 10.14 machine. I haven’t tested on 10.15 yet though.

**Comment by hongkongkiwi** [comment]
I'm running 10.15.4 with bios 059. I havn't set any pmset settings apart from applying the patch.

**Pull request merged**
