### PR TITLE
Add option for DW1820A drivers

### PR DESCRIPTION
**Pull request by osy86**
References #91, #113

### CODE REVIEW

**Comment by osy86** [comment]
Built package: 
[HaCMini.pkg.zip](https://github.com/osy86/HaC-Mini/files/3829752/HaCMini.pkg.zip)

**Comment by osy86** [comment]
Test with the built artifact: https://github.com/osy86/HaC-Mini/suites/304709245/artifacts/291319

**Comment by HorstBrack75** [comment]
> Test with the built artifact: https://github.com/osy86/HaC-Mini/suites/304709245/artifacts/291319

Works fine! THX!

AirportBrcmFixup would not be required for me. WiFi would also work native as "3rd party" on my flavour of DW1820A. 

Maybe there could distinct options for BT and WiFi in the installer?

**Comment by osy86** [comment]
Is there a downside for having AirportBrcmFixup? I don’t want to overload people with choices.

**Comment by HorstBrack75** [comment]
> Is there a downside for having AirportBrcmFixup? I don’t want to overload people with choices.

It is just another kext.... 

But you are right. Probably there is no downside as is it recommended in any case to change the country settings if required.

**Comment by goodbest** [comment]
Work like a charm on my nuc

**Comment by dickding** [comment]
Just bought DW1820A, CN-08PKF4XXX, and it works fine on my nuc.

**Pull request merged**
