### PR TITLE
installer: updated Polaris22Fixup

### LINKED ISSUE #1: Kernel panic in AMD GPU drivers on bootup after 10.14.5 Beta 2
After updating to 10.14.5 Beta 2, kernel panics on boot if GPU acceleration is enabled.

Crash is in `AMDRadeonX4000` but replacing `AMDRadeonX4000HWLibs` with the one from Beta 1 resolves the issue.

Running bindiff and looking at the changes in HWLibs, we identify the following function changes (data only changes and constant operand changes are not identified by bindiff)

A number of functions have bzero added to clear the stack data before use:

_SW_SMUM_Dpm_SetMinDeepSleepDceFClk
_SW_SMUM_Dpm_SetWorkloadPolicy
_SW_SMUM_Dpm_DisableUclkFastSwitching
_SW_SMUM_Dpm_EnableUclkFastSwitching
_SW_SMUM_Dpm_GetCurrentDpm
_SW_SMUM_Dpm_ForceDpmLevel
_SW_SMUM_Dpm_SetClockLimit
_SW_SMUM_Dpm_GetClockLimit

A couple of hardware specific changes may or may not be used by Polaris22 path:

_gc_9_1_init_gfx_power_gating
_gc_10_1_get_gb_addr_config_default
_greenland_update_hw_virtualization_settings
_Cail_Bonaire_UpdateMultimediaClockGating
_PhwCIslands_BugCheckRegisterDump (added register write)
_PhwCIslands_Initialize
_PhwPolaris10_Initialize

Some "suspicious" changes:

_CailIdentifyCrossDisplayAndXGP: check (ulong)(*(int *)(lParm1 + 0x198) - 0x41U < 0x40) for "EnableXDSupport"
_PEM_CWDDEPM_AdjustPowerOptimizationSettings: added blob of code
_CAILFullResetSupport: new branch for *(int *)(lParm1 + 0x19c) - 0x41U < 0x40)
_Cail_MCILQuerySystemInfo: old:0,1 new:0,2
AtiPowerPlayServices::ppInitialize(PPDisplayConfiguration *): call _PP_Initialize => now calls _PP_InitializeEX
_CailReadinRegistryFlags: check (uint)(0x3f < *(int *)(lParm1 + 0x198) - 0x41U) for "DisableFBCSupport"

Other changes that seem benign:
_PEM_CWDDEPM_PMLogControl: removed _PECI_LockPowerPlayOnly/_PECI_UnlockPowerPlayOnly
_PHM_CollectDbgInfo: added indirect call at end
_CailSaveCailInitInfo: added a register copy
_PEM_CWDDEPM_GetODDefaultPerformanceLevels: added assertion
__ZN20AtiPowerPlayServicesC2EP18PowerPlayCallbacks: assertion changes, maybe more
__ZN21AtiPowerPlayInterface25createPowerPlayServiceForEP18PowerPlayCallbacks: assertion changes
__ZN25AtiApplePowerTuneServices23createPowerTuneServicesEP11PP_InstanceP18PowerPlayCallbacks: added navi support
__ZN20AtiAppleMcilServices9obtainIriEPvP22_MCIL_IRI_OBTAIN_INPUTP23_MCIL_IRI_OBTAIN_OUTPUT: removed "ATY,CAIL_IRI"

Trying to individually patch out each change identified here and reverting the behaviour does not appear to fix the issue.

As a workaround, we load the Beta 1 HWLibs and it works normally but can break in a future macOS update.

### LINKED ISSUE #206: Polaris22Fixup patch broken on resume
yesterday I leave my microsoft autoupdater running overnight, the UI of the application showing glitching.
right click on taskbar also found glitchs.

Hac-Mini Release v2.5 installed.
OSX: 10.15.2
LG Ultra HD 5120 x 2880（5K/UHD+ )  scale to 2560 x 1440 @ 60 Hz
AMD Radeon RX Vega M GH

screenshot

### LINKED ISSUE #213: How to enable IGPU for Metal compute?
I need to use the IGPU for Metal compute, separately from the dGPU.

It looks like the default install has the IGPU disabled via the boot-args `-disablegfxfirmware`.   I've removed this, but the IGPU still doesn't show up as a Metal device, nor visible in System Report.  (I have the Intel graphics enabled in the BIOS.)

I see WEG listed in `ioreg`, but it's not matched?

```
    | +-o WhateverGreen  <class WhateverGreen, id 0x100000128, !registered, !matched, active, busy 0, retain 4>
```

Any tips to get the IGPU working?  I have seen that #12 references problems with wakeup, but with my 4K+2K+2K multi-monitor graphics I can't use sleep anyway #7.

- HaC Mini version: 2.6
- OSX version: 10.15.3
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: EVO 970, m.2
- Display port(s) used: 2xUSB-C, 1xDP
- Display resolution(s): 4K, 2K, 2K
- Any TB3 devices: none
- Any USB devices: N/A

### LINKED ISSUE #262: 4K video playback laggy and stuttering.
**Describe the bug**
4K video playback stutters, lots of frame drops.

- Quicktime player: Unable to play.
- IINA: Delays observed.
- VLC: "h264 4k 120-stutter.mp4" unable to play, "h265 4k 60-stutter.mp4" no much problem.

I think it's some configuration problems...
- I can play these two videos in Windows without any problems.
- A MBP 13 plays these smoothly.
- And a Hackintosh build with AMD 2700x CPU and Radeon Vega II GPU can correctly hardware decode these videos OOB.

Video links:https://1drv.ms/u/s!Aj4tLSaqxvfdwjASwip9MKVr3I2o?e=sY6t90
password: hacmini
(just some random videos for testing...)

**Expected behavior**
Should decoding correctly and playing smoothly. 

**Configuration**
- HaC Mini version : 2.7
- OSX version : 10.15.4
- NUC model : HVK
- Display port(s) used : MINIDP, USB-C
- Display resolution(s) : 2K, 4K

**Modifications**
I tried the both AMD codec and Intel codec of the HacMini Installer, nothing changed.
It only plays these videos smoothly when HW acc is not available...(Using software decoding).

(Later, I changed my PlatformInfo to iMac18,3, which is nothing to do with this problem tho.
Btw, I saw you have talked about the iMac18,3 and USB-C DP in some Issues, but I've tested and it works fine. Would you like to consider making the iMac18,3 option available in the installer?)

### PR DESCRIPTION
**Pull request by osy86**
* Use Lilu again
* Patch works on resume (fixes #206)
* Fix kernel panic on bootup without workaround (fixes #1)
* Above means booting with latest AMD GPU drivers works, this may fix other
  issues as well.
* 4K stuttering issue resolved by using AMD codec (fixes #262)
* Enable offline compute for IGPU (fixes #213)

### CODE REVIEW

**Comment by iiicwx** [comment]
Thank you @osy86 , just test it, Apple TV+ works again, still have to go through a sleep though.

**Comment by osy86** [comment]
That’s weird I still can’t get it to work just as before.

**Comment by iiicwx** [comment]
@osy86 maybe mini dp to dp? @crhendo also uses mini dp who confirmed me on #131

**Comment by osy86** [comment]
I am currently using miniDP to DP running on 10.15.5. My monitor is a LG 4k 60hz display with freesync. HDCP is enabled. I tried both amd codec option and intel codec option.

**Comment by osy86** [comment]
@KrisCris I've updated the package so Intel option also uses AMD decoder and Intel encoder (AMD option uses AMD encoder+decoder). So sidecar should work. Make sure to select "reset boot-args" when installing as the boot-args have changed.

Also due to a bug in macOS, sandboxed apps like Quicktime cannot read the AppleGVA settings. So you have to test with the TV app or iTunes app.

**Comment by crhendo** [comment]
I would like to give this a try however I lack the skills on how to install these new branches. Is there an updated HaCMini.pkg file that I can access or something I should read that would give me a clue on how to test new branches?

As always, any help would be very much appreciated.

**Comment by osy86** [comment]
https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#downloading-or-deleting-artifacts

**Comment by goodbest** [comment]
I don't have issue #1 #262 or #206 previously, so I couldn't help testing this PR for those issue..

For the DRM thing, I don't know if I'm alone. 
Intel Codec: 
 - Apple TV+ Episodes (with fp4? hw4 maybe), video = Black screen, audio = fine
 - Purchased iTunes Episodes (with fp1? sw maybe), work fine.

AMD Codec:
 -  Apple TV+ Episodes (with fp4? hw4 maybe), video = green glitches, audio = fine
 - Purchased iTunes Movie (with fp1? sw maybe), work fine.

----
By the way, 
In WEG Shiki, it says AMD Polaris Ellesmere is broken in 10.15 (e.g. RX 590).
Not sure whether it's still the case in 10.15.5
https://github.com/acidanthera/WhateverGreen/blob/a5abdbd7dffc85ebbddbac19a1820873b280b214/WhateverGreen/kern_shiki.hpp#L72

**Comment by osy86** [comment]
https://github.com/osy86/HaC-Mini/issues/1#issuecomment-583056056 Claims it’s fixed

**Comment by iiicwx** [comment]
tried the test built 71&73, apple tv+ not working.

**Comment by osy86** [comment]
Those are the wrong branch. 69 is the latest one for this branch.

**Pull request merged**
