### PR TITLE
installer: add itlwm driver

### LINKED ISSUE #322: SUGGESTION: incorporate stable release of OpenIntelWireless itlwm(x) and IntelBluetooth
Hi @osy86 !

This recent iteration (2.11) has been great. Everything is running smoothly in my macOS 1.14.6 Mojave setup.

Was wondering if the installer can roll-in [OpenIntelWireless](https://github.com/OpenIntelWireless) project's [itlwm(x)](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.0.0) (along with adding in release [1.1.2](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/tag/1.1.2) of IntelBluetoothFirmware). Note that _if_ the user installs either itlwm or itlwmx, then it should also install [HeliPort ](https://github.com/OpenIntelWireless/HeliPort/releases/tag/v1.0.0) for easy WiFi control by the user.

It would be an "exclusive OR" checkmark, as users cannot use both `itlwm` and `itlwmx` at the same time. The default for the original WiFi m.2 that comes with the Intel Hades Canyon NUC should be `itlwm`.

Note: these kexts provide WiFi speeds for 5GHz best, and max out around `80 megabit` _download_ and `20 megabit` _upload_. This is "good enough" for average internet use.

### PR DESCRIPTION
**Pull request by osy86**
Fixes #322

### CODE REVIEW

**Comment by osy86** [comment]
@Malumen please test

**Comment by Malumen** [comment]
> @Malumen please test

Hi @osy86 
I will! I just don't know how. Do I just redownload the installer `.pkg` file and run it again?

**Comment by shian15810** [comment]
@Malumen You can download the built installer from CI, which is https://github.com/osy86/HaC-Mini/suites/1274940312/artifacts/19679451.

**Comment by Malumen** [comment]
@shian15810  谢谢告诉了我怎么做

@osy86  it seems to work OK! I'll upload a screenshot after my 1,000 pingtest and speedtest (fast.com) are done. The kext shows Ethernet 3 as WiFi so the HaC mini thinks it has a third LAN port... And HeliPort allows me to see and connect to networks nearby like a real Mac's WiFi. Very cool!

**Comment by Malumen** [comment]
Screen Shot 2020-10-05 at 8 30 35 PM

Pretty good!

**Pull request merged**
