### PR TITLE
Updated acidanthera projects

### PR DESCRIPTION
**Pull request by osy86**
AppleALC 1.4.4
AppleSupport 2.1.4
Lilu 1.4.0
MacInfo 2.0.9
OpenCore 0.5.3
WhateverGreen 1.3.5

### CODE REVIEW

**Comment by lmshsqlc** [comment]
So further on we community can use pull request to keep this repository running?

**Comment by osy86** [comment]
Yes, when you update the link + SHA and make a pull request, it should automatically build the package ex: https://github.com/osy86/HaC-Mini/suites/344597448/artifacts/567531

**Comment by goodbest** [comment]
I think it's better to use `shikigva=160` instead of 32 for weg >=1.3.5 ? 
(At lease you can hear the audio of offline drm files)

**Comment by osy86** [comment]
I want to try to fix the issue first before merging this.

**Comment by osy86** [comment]
Let's try to fix the DRM issues in a separate pull request. The updated projects don't introduce any new problems.

**Pull request merged**
